version: '3.8'
services:
  mpd:
    # image: aoirint/mpd:20220629.1
    image: aoirint/mpd:latest
    restart: always
    group_add:
      - '${HOST_AUDIO_GROUP}'
    ports:
      - '${HOST_MPD_PORT}:6600'
      - '${HOST_HTTP_PORT}:8000'
    environment:
      PULSE_SERVER: ${PULSE_SERVER}
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      MPD_PASSWORD: ${MPD_PASSWORD}
    volumes:
      - '${HOST_PULSE_NATIVE_FILE}:${HOST_PULSE_NATIVE_FILE}'
      - '${HOST_PULSE_COOKIE_FILE}:/pulseaudio/cookie'
      - './data/music:/mpd/music'
      - './data/playlists:/playlists'
      - './data/log:/mpd/log'

